from app import db


class MovieRating(db.Model):
    __tablename__ = 'movierating'
    imdbID = db.Column(db.String, primary_key=True)
    Title = db.Column(db.String)
    imdbRating = db.Column(db.String)
    Poster = db.Column(db.String)
    Ratings = db.Column(db.Text)
    # timestamps disabled by default in Flask-SQLAlchemy (no created_at/updated_at)


# class FreeUpcomingMr(db.Model):
#     __tablename__ = 'free_upcomming_mr'
#     id = db.Column(db.Float, primary_key=True)
#     tmid = db.Column(db.String)
#     imdb_id = db.Column(db.String)
#     title = db.Column(db.String)
#     plot = db.Column(db.Text)
#     language = db.Column(db.String)
#     popularity = db.Column(db.String)
#     poster_path = db.Column(db.String)
#     release_date = db.Column(db.String)
#     revenue = db.Column(db.String)
#     runtime = db.Column(db.String)
#     status = db.Column(db.String)
#     tagline = db.Column(db.String)
#     video = db.Column(db.String)
#     vote_average = db.Column(db.String)
#     vote_count = db.Column(db.String)
#     website = db.Column(db.String)
#     genre = db.Column(db.String)
#     posters = db.Column(db.Text)
#     backdrops = db.Column(db.Text)
#     trailers = db.Column(db.Text)
#     prod_companies = db.Column(db.Text)
#     prod_country = db.Column(db.Text)
#     cast = db.Column(db.Text)
#     crew = db.Column(db.Text)
#     streming_urls = db.Column(db.Text)
#     country_code = db.Column(db.String)
#     country_name = db.Column(db.String)
#     genre_text = db.Column(db.String)
#     poster_url = db.Column(db.String)
#     wikimedia = db.Column(db.Text)
#     translated_plot = db.Column(db.Text, default=None, nullable=True)
#     original_title = db.Column(db.String, default=None, nullable=True)
#     translated_cast = db.Column(db.Text, default=None, nullable=True)
#     translated_crew = db.Column(db.Text, default=None, nullable=True)

# class FreeTopratedMr(db.Model):
#     __tablename__ = 'free_toprated_mr'
#     id = db.Column(db.Float, primary_key=True)
#     tmid = db.Column(db.String)
#     title = db.Column(db.String)
#     plot = db.Column(db.Text)
#     language = db.Column(db.String)
#     popularity = db.Column(db.String)
#     poster_path = db.Column(db.String)
#     release_date = db.Column(db.String)
#     revenue = db.Column(db.String)
#     runtime = db.Column(db.String)
#     status = db.Column(db.String)
#     tagline = db.Column(db.String)
#     video = db.Column(db.String)
#     vote_average = db.Column(db.String)
#     vote_count = db.Column(db.Float)
#     website = db.Column(db.String)
#     genre = db.Column(db.String)
#     posters = db.Column(db.Text)
#     backdrops = db.Column(db.Text)
#     trailers = db.Column(db.Text)
#     prod_companies = db.Column(db.Text)
#     prod_country = db.Column(db.Text)
#     cast = db.Column(db.Text)
#     crew = db.Column(db.Text)
#     imdb_id = db.Column(db.String)
#     streaming_urls = db.Column(db.Text)
#     genre_text = db.Column(db.String)
#     country_code = db.Column(db.String)
#     country_name = db.Column(db.String)
#     poster_url = db.Column(db.String)
#     wikimedia = db.Column(db.Text)
#     translated_plot = db.Column(db.Text, default=None, nullable=True)
#     original_title = db.Column(db.String, default=None, nullable=True)
#     translated_cast = db.Column(db.Text, default=None, nullable=True)
#     translated_crew = db.Column(db.Text, default=None, nullable=True)


# class FreeMoviesDetails(db.Model):
#     __tablename__ = 'freemoviedetail'
#     adult = db.Column(db.Boolean)
#     backdrop_path = db.Column(db.String)
#     belongs_to_collection = db.Column(db.String)
#     budget = db.Column(db.Float)
#     genres = db.Column(db.String)
#     homepage = db.Column(db.String)
#     id = db.Column(db.Float, primary_key=True)
#     imdb_id = db.Column(db.String)
#     original_language = db.Column(db.String)
#     original_title = db.Column(db.String)
#     overview = db.Column(db.Text)
#     popularity = db.Column(db.Float)
#     poster_path = db.Column(db.String)
#     production_companies = db.Column(db.Text)
#     production_countries = db.Column(db.String)
#     release_date = db.Column(db.String)
#     revenue = db.Column(db.Float)
#     runtime = db.Column(db.Float)
#     spoken_languages = db.Column(db.Text)
#     status = db.Column(db.String)
#     tagline = db.Column(db.String)
#     title = db.Column(db.String)
#     video = db.Column(db.Boolean)
#     vote_average = db.Column(db.Float)
#     vote_count = db.Column(db.Float)
#     cast = db.Column(db.Text)
#     crew = db.Column(db.Text)
#     videos = db.Column(db.Text)
#     link = db.Column(db.Text)
#     flatrate = db.Column(db.Text)
#     free = db.Column(db.Text)
#     translated_plot = db.Column(db.Text, default=None, nullable=True)
#     translated_cast = db.Column(db.Text, default=None, nullable=True)
#     translated_crew = db.Column(db.Text, default=None, nullable=True)
