from app import db


class MovieDetails(db.Model):
    __tablename__ = 'moviedetails'
    adult = db.Column(db.Boolean)
    backdrop_path = db.Column(db.String)
    belongs_to_collection = db.Column(db.Text)
    budget = db.Column(db.Float)
    genres = db.Column(db.String)
    homepage = db.Column(db.String)
    id = db.Column(db.BigInteger, primary_key=True)
    imdb_id = db.Column(db.String)
    original_language = db.Column(db.String)
    original_title = db.Column(db.String)
    overview = db.Column(db.Text)
    popularity = db.Column(db.Float)
    poster_path = db.Column(db.String)
    production_companies = db.Column(db.Text)
    production_countries = db.Column(db.String)
    release_date = db.Column(db.String)
    revenue = db.Column(db.Float)
    runtime = db.Column(db.Float)
    spoken_languages = db.Column(db.Text)
    status = db.Column(db.String)
    tagline = db.Column(db.String)
    title = db.Column(db.String)
    video = db.Column(db.Boolean)
    vote_average = db.Column(db.Float)
    vote_count = db.Column(db.Float)
    cast = db.Column(db.Text)
    crew = db.Column(db.Text)
    videos = db.Column(db.Text)
    link = db.Column(db.Text)
    flatrate = db.Column(db.Text)
    free = db.Column(db.Text)
    buy = db.Column(db.Text)
    rent = db.Column(db.Text)
    streaming_urls = db.Column(db.Text)
    translated_plot = db.Column(db.Text, default=None, nullable=True)
    translated_cast = db.Column(db.Text, default=None, nullable=True)
    translated_crew = db.Column(db.Text, default=None, nullable=True)